apiVersion: v1
kind: Pod
metadata:
  labels:
    run: girus
    service: webserver
  name: girus
spec:
  containers:
  - image: ubuntu
    name: ubuntu
    resources:
      limits:
        cpu: "0.5"
        memory: "128Mi"
      requests:
        cpu: "0.3"
        memory: "64Mi"
    args:
      - sleep
      - "6000"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
